### ISSUE TITLE
dashArray should be an array

### ISSUE THREAD

**Issue by pcurrivan** [adammertel/Leaflet.MarkerCluster.PlacementStrategies#6]
dashArray in clockHelpingCircleOptions is set to the number 5.  At least on Firefox, this results in an error with the canvas renderer.  It should be an array (I think string works too).

see https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/setLineDash

**Comment by adammertel** [comment]
Hi pcurrivan, 
thank you for reporting this issue. 
The thing is that this plugin was mostly tested with SVG renderer as it is recommended for Leaflet. And in SVG, `dashArray` property value is a string https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-dasharray

Anyway, in my FF (v 72.0.1 (64-bit)), the `dashArray` variable rendered correctly for helping circle. What version do you use? 
![image](https://user-images.githubusercontent.com/12932677/77457085-79bf7c80-6dfc-11ea-92fa-6b563c6a9a99.png)

Last, but not least, this issue is also stated in the leaflet documentation.
![image](https://user-images.githubusercontent.com/12932677/77457583-30236180-6dfd-11ea-9fc3-77b3c179b0bd.png)

Adam

**Comment by pcurrivan** [comment]
I'm on the latest Firefox (75).  I can confirm the error goes away when I set preferCanvas to false in the Leaflet options.

> in SVG, dashArray property value is a string https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-dasharray

Doesn't that say the value is a list?  Like all HTML attributes it is encoded as a string in HTML.  It looks like Leaflet uses setAttribute on the SVG element, which turns your 5 into "5", then the browser's SVG renderer parses the attribute "5" into an array.  That's the only reason using a number works with SVG.  With canvas there is no element involved so there is no magic type conversion via string formatting and parsing.  At least that's my understanding.

**Comment by adammertel** [comment]
According to leaflet documentation, `dashArray` value is a String. Also, there is a special method turning this string value to array when the Canvas renderer is set (see `_updateDashArray` method here https://github.com/Leaflet/Leaflet/blob/d1a1e97b8290f642eb677284af53c2db64199a76/src/layer/vector/Canvas.js)

**Comment by pcurrivan** [comment]
https://github.com/adammertel/Leaflet.MarkerCluster.PlacementStrategies/blob/master/dist/leaflet-markercluster.placementstrategies.src.js#L385

Sorry if I was unclear, the issue is that dashArray is set to a number here, *not a string*.  I just confirmed that string and array both work for svg and canvas.

**Comment by adammertel** [comment]
No problem, I should have read your first comment one more time. 
In this case, I agree with you - this is really a mistake in my code. I will take care of it this weekend.
Once again - thank you very much for reporting.
Adam
